### ISSUE TITLE
Suggestions for the documentation

### ISSUE THREAD

**Issue by ignacio82** [daqana/dqrng#13]
These suggestions come from someone who is very new at Rcpp, I just took the datacamp course last weekend:

1. Add additional comments for people who are new to c++ whenever possible (experts can ignore them but for people like me they can be very valuable). For example:

```
#include <Rcpp.h>
// [[Rcpp::depends(dqrng)]]
#include <xoshiro.h> 
#include <dqrng_distribution.h>
// [[Rcpp::plugins(openmp)]]
#include <omp.h>

// [[Rcpp::plugins(cpp11)]]  /// Why/where are you using this plugin? 
// [[Rcpp::export]]
std::vector<double> parallel_random_sum(int n, int m, int ncores) {
  dqrng::uniform_distribution dist(0.0, 1.0);  // Uniform distribution [0,1]
  dqrng::xoshiro256plus rng(42); // Set seed for random numbers
  std::vector<double> res(m);
  // ok to use rng here
  
  #pragma omp parallel num_threads(ncores)
  {
    dqrng::xoshiro256plus lrng(rng);      // make thread local copy of rng 
    lrng.jump(omp_get_thread_num() + 1);  // advance rng by 1 ... ncores jumps 
    auto gen = std::bind(dist, std::ref(lrng));  // creates a random number generator that draws from dist with seed lrng

    #pragma omp for
    for (int i = 0; i < m; ++i) {
      double lres(0);
      for (int j = 0; j < n; ++j) {
        lres += gen();
      }
      res[i] = lres / n;
    }
  }
  // ok to use rng here
  return res;
}

```

I would also suggest adding [the example you helped me create in StackOverflow](https://stackoverflow.com/questions/54756648/rstudio-crashes-with-rcpp-and-openmp-function/54760254#54760254). That little example shows a few things that were very helpful for me:

1. It shows how to use distributions from boost
2. it shows how to use multiple distributions at the same time
3. It shows how to make the parameters of the distribution be a function of `i` and `j`

I'm sure all these things are obvious for an experienced c++ programmer, but for a newcomer like me, this little example could be beneficial. 

Finally, I'm not sure if you have a close relationship with the developers of Rcpp, but I think creating a forum like discourse could be great for its community. For example, Stan and Rstudio did it. In my personal experience, a lot of people are intimidated by StackOverflow, and they avoid asking questions there. I think this is particularly true for people who are new to a topic.

Best,

Ignacio

PS: Thanks for all the help you gave me and for your amazing package!

**Comment by rstub** [comment]
Thanks for the suggestions. I will definitely add more comments in the code. The extended example looks also interesting.

The alternative to SO for Rcpp related question would be the [Rcpp mailing list](http://lists.r-forge.r-project.org/pipermail/rcpp-devel/).

**Comment by ignacio82** [comment]
Thanks. Would you mind answering this question?

```
// [[Rcpp::plugins(cpp11)]]  /// Why/where are you using this plugin?
```

I noticed that the code runs if I delete that line so I'm not sure why is there.

**Comment by ignacio82** [comment]
btw, [this](https://stackoverflow.com/questions/54809461/is-there-a-way-to-assign-column-names-to-an-armamat-inside-a-c-function) is why i suggested doing what Stan or Rstudio does for community instead of StackOverflow:

![image](https://user-images.githubusercontent.com/1833309/53179619-0d06fc80-35c2-11e9-8977-81c48b0baf28.png)

I know my question is stupid, I'm learning on nights and weekends so I'm bound to ask stupid questions... Honestly, I can take the negative nudge from StackOverflow but I know plenty of people who just avoid asking questions there because of these type of thing.

**Comment by rstub** [comment]
> ```
> // [[Rcpp::plugins(cpp11)]]  /// Why/where are you using this plugin?
> ```

```
    auto gen = std::bind(dist, std::ref(lrng));
    ^^^^
```

The `auto` keyword requires C++11. I think that's the only thing in this piece of code, but I might be wrong.

> I noticed that the code runs if I delete that line so I'm not sure why is there.

This means that your compiler uses C++11 by default, which is quite normal for recent compilers. But one cannot assume that the default compiler used by R behaves like that.

**Comment by rstub** [comment]
I have looked at the code on SO again, and I still find it interesting to add it one way or another. Some observations:

* The code is already quite complex, even though the parameter `p ` does not depend on the iteration yet. But it still feels artificial. Can you give a "business description" of the use case you have in mind?

* Do you think the parallel code is necessary for the example? Without the parallel parts the example could go into the general vignette.

**Comment by ignacio82** [comment]
The reason I want to be able to draw from those distributions is that I want to do predictions after fitting a model with [Stan](https://mc-stan.org/). Typically you would do these predictions within your Stan code, but for my particular use case, that would be suboptimal. 

In particular, I want to do predictions for [a new observation in a new group](https://discourse.mc-stan.org/t/prediction-for-a-new-observation-in-a-new-group/7427).

**Comment by rstub** [comment]
The code from the vignette can actually be simplified, making some comments unnecessary:

```cpp
#include <Rcpp.h>
// [[Rcpp::depends(dqrng)]]
#include <xoshiro.h>
#include <dqrng_distribution.h>
// [[Rcpp::plugins(openmp)]]
#include <omp.h>

// [[Rcpp::export]]
std::vector<double> parallel_random_sum(int n, int m, int ncores) {
  dqrng::uniform_distribution dist(0.0, 1.0); // Uniform distribution [0,1)
  dqrng::xoshiro256plus rng(42);              // properly seeded rng
  std::vector<double> res(m);
  // ok to use rng here
  
  #pragma omp parallel num_threads(ncores)
  {
    dqrng::xoshiro256plus lrng(rng);      // make thread local copy of rng 
    lrng.jump(omp_get_thread_num() + 1);  // advance rng by 1 ... ncores jumps

    #pragma omp for
    for (int i = 0; i < m; ++i) {
      double lres(0);
      for (int j = 0; j < n; ++j) {
        lres += dist(lrng);
      }
      res[i] = lres / n;
    }
  }
  // ok to use rng here
  return res;
}

/*** R
parallel_random_sum(1e7, 8, 4)
*/
```

Do you see anything else that needs commenting?

As for the more complex example, I would like to use a serial version without RcppArmadillo in the normal vignette, e.g.:

```cpp
#include <Rcpp.h>
// [[Rcpp::depends(dqrng, BH)]]
#include <boost/random/binomial_distribution.hpp>
#include <boost/random/normal_distribution.hpp>
#include <xoshiro.h>

// [[Rcpp::export]]
Rcpp::NumericMatrix multiple_distributions(int n, int m, double p=0.5) {
  dqrng::xoshiro256plus rng(42);
  Rcpp::NumericMatrix out(n*m,3);
  // one fixed distribution
  boost::random::normal_distribution<double> normal1(2.0,1.0);
  int iter = 0;
  for (int i = 0; i < m; ++i) {
    for (int j = 0; j < n; ++j) {
      iter = i * n + j;
      // p can be a function of i and j
      boost::random::binomial_distribution<int> binomial(1,p);
      // this could also depend on i, j
      boost::random::normal_distribution<double> normal2(4.0,3.0);
      out(iter,0) = binomial(rng);
      out(iter,1) = normal1(rng);
      out(iter,2) = normal2(rng);
    }
  }
  return out;
}

/*** R
multiple_distributions(5, 5, 0.75)
*/
```

Do you see anything else that is worth mentioning?

**Comment by ignacio82** [comment]
This looks great, I would make only one addition to the second example.  Before returning `out` I would add names to its columns:

```cpp
colnames(out) = CharacterVector::create("Bernoulli", "Normal(2,1)", "Normal(4,3)");
```

I know this is probably obvious for most people, but it coul be useful for a newbie.

**Comment by rstub** [comment]
Good idea. 

I have made some further refinements:

* There is no need for a double loop.
* Make the parameters actually depend on iteration status.
* Use `param_type` to change the parameters of an existing distribution object.

> For some applications it is necessary to draw random numbers from multiple distributions with varying parameters. The following function uses a binomial distribution (fromm `boost.random`) as well as the normal distribution from `dqrng`. The parameters of the distributions are adjusted for every draw using `<distribution>::param_type`: 
>
```cpp
#include <Rcpp.h>
// [[Rcpp::depends(dqrng, BH)]]
#include <boost/random/binomial_distribution.hpp>
#include <dqrng_distribution.h>
#include <xoshiro.h>

// aliases for the used ditributions
using binomial = boost::random::binomial_distribution<int>;
using normal = dqrng::normal_distribution;
// [[Rcpp::export]]
Rcpp::NumericMatrix multiple_distributions(int n) {
  dqrng::xoshiro256plus rng(42);
  // distributions with default parameters
  binomial bernoulli;
  normal normal1;
  normal normal2;
  Rcpp::NumericMatrix out(n, 3);
  double p = 0.0;
  for (int i = 0; i < n; ++i) {
    p = double(i) / double(n);
    out(i,0) = bernoulli(rng, binomial::param_type(1, p));
    out(i,1) = normal1(rng, normal::param_type(p, 1.0));
    out(i,2) = normal2(rng, normal::param_type(4.0, 3.0 - p));
  }
  Rcpp::colnames(out) = Rcpp::CharacterVector::create("Bernoulli", "Normal1", "Normal2");
  return out;
}

/*** R
multiple_distributions(5)
*/
```

Please let me know if you find anything difficult to understand.

**Comment by ignacio82** [comment]
I like it, but I have a couple of questions for my own education:

1. You replaced `boost/random/normal_distribution.hpp` for  `#include <dqrng_distribution.h>`. Why?
2.  You are now using `binomial::param_type`, could you point me to the documentation so I can better understand how this is different from what I was doing before?

Thanks!

**Comment by rstub** [comment]
1. Because I am using `dqrng::normal_distribution` instead of `boost::random::normal_distribution<double>` . These are the same, but it felt more natural to use dqrng features in the dqrng vignette ;-)

2. I got that from section 9 in https://isocpp.org/files/papers/n3551.pdf. That is about C++11's `random`, but `boost.random` works the same (in most cases).

**Comment by rstub** [comment]
Fixed in eef009f1062b7aca27c59524b9e86f2be3571041 and 355e0e1ed09a7b8f1b4e21bf9476e128b43917b2.

**Comment by ignacio82** [comment]
I have a follow up question. Could these lines:

```
out(i,1) = normal1(rng, normal::param_type(p, 1.0));
out(i,2) = normal2(rng, normal::param_type(4.0, 3.0 - p));
```

be replaced with

```
out(i,1) = normal1(rng, normal::param_type(p, 1.0));
out(i,2) = normal1(rng, normal::param_type(4.0, 3.0 - p));
```

?? Why do you need to have two different functions?

**Comment by rstub** [comment]
You are correct, one instance of `normal_distribution` is enough. I will adjust that right away.
