### ISSUE TITLE
duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by isezen** [daqana/dqrng#28]
Hello,
I created a simple minimal [R package](https://github.com/isezen/dqrngtest) to reproduce the following compile error. If I include the `dqrng_distribution.h` or similar files into more than one `.cpp` file, I'm getting the following error. I believe those functions are not inline in header files but I might be wrong. Is there a workaround to overcome this issue or did I stuck to a single `.cpp` file?

```
duplicate symbol __ZN5dqrng20random_64bit_wrapperIN10pcg_detail6engineIyoNS1_12xsl_rr_mixinIyoEELb0ENS1_15specific_streamIoEENS1_18default_multiplierIoEEEEE4seedEyy in:
    rcpp1.o
    stat.o
duplicate symbol __ZN5dqrng20random_64bit_wrapperINS_7xoshiroILm2ELa24ELa16ELa37EEEE4seedEyy in:
    rcpp1.o
    stat.o
duplicate symbol __ZN5dqrng20random_64bit_wrapperINS_7xoshiroILm4ELa17ELa45ELa0EEEE4seedEyy in:
    rcpp1.o
    stat.o
duplicate symbol __ZN5dqrng20random_64bit_wrapperIN5sitmo15threefry_engineIyLm64ELm20EEEE4seedEyy in:
    rcpp1.o
    stat.o
ld: 4 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by LTLA** [comment]
I can't even get it to compile, let alone link. It seems `xoshiro.h` could do with:

```cpp
#include <functional>
#include <algorithm>
#include <type_traits> // just in case.
```

... while your `stat.hpp` needs:

```cpp
#include <functional>
#include <vector>
```

Presumably your compiler drags in those headers with something else that got `#include`d, so you don't see a problem, but other implementations may not do so. In this case, I'm failing with GCC 7.4.0.

Anyway, onto the actual problem. The template specialized functions in `dqrng_generator.h` need to be `inline`d to bypass the one-definition rule. See #29; I didn't do them all, but we probably should.

**Comment by isezen** [comment]
similar problem exist here, too.
https://github.com/daqana/dqrng/blob/816de867c43e3f551bd7a8d05e0e3371a2503c2b/inst/include/convert_seed.h#L23-L38
