### ISSUE TITLE
Provide access to the global RNG

### ISSUE THREAD

**Issue by rstub** [daqana/dqrng#41]
For some applications it makes sense to use a RNG directly. It is of course always possible to generate a new RNG, but that has its own independent state. It would be more convenient, if one could get access to (a shared pointer holding) the global RNG.

**Comment by hsloot** [comment]
I have thought a little bit about how to do this and came up with the following solution. It should be possible to wrap the shared_ptr `rng` as a static member in another class which initialises the shared_ptr, the first time an instance is created. 

``` C++
namespace dqrng {

template<typename C>
class ObjectCounter {
public:
  ObjectCounter() {++totalObjects_;}
  ObjectCounter(const ObjectCounter& obj) {if(this != &obj) ++totalObjects_;}
  ~ObjectCounter() {--totalObjects_;}

  static size_t OustandingObjects() {return totalObjects_;}

private:
  static size_t totalObjects_;
};

class DQRNG : private ObjectCounter<DQRNG> {
public:
  DQRNG();
  ~DQRNG();

  static dqrng::rng64_t shared_rng;
};

#ifndef DQRNG_TOTAL
#define DQRNG_TOTAL
template<>
size_t ObjectCounter<DQRNG>::totalObjects_ = 0;
#endif // DQRNG_TOTAL

DQRNG::DQRNG() {
  if (this->OustandingObjects() == 1) {
    GetRNGstate();
    Rcpp::IntegerVector seed(2, dqrng::R_random_int);
    shared_rng = dqrng::generator(dqrng::convert_seed<uint64_t>(seed));
  }
}

DQRNG::~DQRNG() {
  if (this->OustandingObjects() == 1) {
    // no call to PutRNGstate() required?!
  }
}

dqrng::rng64_t DQRNG::shared_rng;

} // dqrgn
```


Sampling from the exponential distribution could then be facilitated as follows 

``` C++
namespace dqrng {

class ExpGenerator  {
public:
  ExpGenerator();
  ExpGenerator(double rate = 1.);

  inline double operator()() const;
private:
  dqrng::exponential_distribution exp;
  const DQRNG rng;
}; // ExpGenerator

ExpGenerator::ExpGenerator() :
  ExpGenerator(1.) {}

ExpGenerator::ExpGenerator(double rate) {
  using parm_t = decltype(exp)::param_type;
  exp.param(parm_t(rate));
}

inline double ExpGenerator::operator()() const {
  return exp(*rng.shared_rng);
}

}
```

For most of the other distributions, it should work in the same way ...

Then, in `scr/dqrng.cpp`, one simply has to include 

```C++
// ... headers
namespace {
dqrgn::DQRNG shared_dqrng = dqrgn::DQRNG();
}

// ... other stuff 
//' @export
// [[Rcpp::export(rng=false)]]
NumericVector dqrexp(R_xlen_t n, double rate = 1.) {
  NumericVector out(no_init(n));
  dqrgn::ExpGenerator<dqrng::DQRNG> gen(rate);
  std::generate(out.begin(), out.end(), gen);

  return out;
}
```

I got carried away a little bit and wrote a small package which implements this with a few tests and also outlines in the README a possible use-case (that would mainly be my interest in the whose thing). You can look at that here: [https://github.com/hsloot/RcppRNG](https://github.com/hsloot/RcppRNG).

**Comment by hsloot** [comment]
I revisited the issue and noticed that my previous suggestion was not helpful. I came up with an alternative, simple approach (see https://github.com/hsloot/dqrng) using an `Rcpp::XPtr` to expose the underlying raw pointer to the RNG. This seems to work (also in parallel clusters. Benchmarks show that this approach comes with little to no overhead (see https://github.com/hsloot/dqrng/blob/master/performance/global_rng.md). 

If you like the approach, I could provide a PR. 

## Notes on the implementation 

The following method can be used to expose the raw pointer to the global RNG in an `Rcpp::XPtr`. 

```cpp
// src/dqrng.cpp
...
// after rng is initialized
// [[Rcpp::export(rng = false)]]
SEXP get_sxprng() {
  return Rcpp::XPtr<dqrng::rng64_t::element_type>(rng.get(), false);
}
```

This creates bindings via the Rcpp interface in `dqrng_RcppExports.h`. Using this method directly would be a little difficult, so I created a wrapper method intended to be used by others in a separate header `dqrng_get_rng.h`.

```cpp
// inst/include/dqrng_get_rng.h
#ifndef DQRNG_GET_RNG_H
#define DQRNG_GET_RNG_H 1

#include <Rcpp.h>
#include "dqrng.h"
#include "dqrng_generator.h"

namespace dqrng {

dqrng::rng64_t::element_type* get_rng() {
	return Rcpp::XPtr<dqrng::rng64_t::element_type>(dqrng::get_sxprng()).get();
}

}

#endif // DQRNG_GET_RNG_H
```

## Alternatives

I am not sure if it is also possible to directly expose the shared_ptr or the raw pointer without going through the `Rcpp::XPtr`; however, I could not make this to work.

**Comment by rstub** [comment]
Hi @hsloot. 
Sorry for the late reply. I had missed your comments, but came to a similar solution when I started playing around with it, c.f. https://github.com/daqana/dqrng/tree/access-rng. Would you still be interested in providing a PR?

**Comment by hsloot** [comment]
I tried merging both approaches and cleaning it up a bit; see #58.
