### ISSUE TITLE
A note of appreciation

### ISSUE THREAD

**Issue by LTLA** [daqana/dqrng#8]
Just a note of appreciation for making this nice package - saved me some trouble packaging up the `pcg` headers myself. CRAN doesn't record reverse dependencies to BioC packages, but here they are:

https://www.bioconductor.org/packages/devel/bioc/html/DropletUtils.html
https://www.bioconductor.org/packages/devel/bioc/html/scran.html

This being an issue, I guess I should complain about _something_; so, could we get the latest versions of the PCG C++ headers? There's a couple of small changes to what's currently available in _dqrng_.

**Comment by rstub** [comment]
Thanks for the kind words! I have updated the PCG headers now.

Concerning improvements w.r.t. seeding: Could you open a separate issue for this? Thanks.
